name: CI
on:
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update KeepAlive.txt
        run: |
          echo $(cat /proc/sys/kernel/random/uuid) > KeepAlive.txt

      - name: Commit file KeepAlive.txt
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          bash script/ci.sh \
          ${{ secrets.GITHUB_TOKEN }} \
          ${github.repository} \
          "KeepAlive.txt" \
          "KeepAlive.txt Update to version $(TZ='Asia/Shanghai' date +'%Y-%m-%d')" \
          "Signed-off-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
