name: CI
on:
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Update KeepAlive.txt
        run: |
          echo $(cat /proc/sys/kernel/random/uuid) > KeepAlive.txt

      - name: Commit file KeepAlive.txt
        run: |
          bash script/ci.sh \
          ${{ secrets.CI_GITHUB_TOKEN }} \
          "maboloshi/inuyasha" \
          "KeepAlive.txt" \
          "KeepAlive.txt Update to version $(TZ='Asia/Shanghai' date +'%Y-%m-%d')" \
          "Signed-off-by: 沙漠之子 <7850715+maboloshi@users.noreply.github.com>"
