name: CI
on:
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update KeepAlive.txt
        run: |
          echo $(cat /proc/sys/kernel/random/uuid) > KeepAlive.txt

      - name: Commit file KeepAlive.txt
        # env:
          # GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          # echo "$GITHUB_CONTEXT"
          bash script/ci_commit_with_signature.sh \
          ${{ secrets.GITHUB_TOKEN }} \
          ${{ github.repository }} \
          ${{ github.ref_name }} \
          ${{ github.sha }} \
          "KeepAlive.txt" \
          "KeepAlive.txt Update to version $(TZ='Asia/Shanghai' date +'%Y-%m-%d')"
