name: Variable test
on:
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: output variable1
        run: |
          echo ${{ github.repository }}
          echo ${{ github.repository_owner }}
          echo ${{ env.GITHUB_REPOSITORY }}

      - name: output variable2
        run: echo "$GITHUB_REPOSITORY_OWNER"

      - name: output variable3
        run: echo "$GITHUB_REPOSITORY"

      - name: output variable4
        run: echo $GITHUB_REPOSITORY # 注意这种表达式 只能在单行run中有效 ,在 `run: |`中会报错

