name: Update contributors images in README.md
on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Contributors Images
        uses: jaywcjlove/github-action-contributors@v1.3.5
        id: contributors
        with:
          filter-author: (renovate\[bot\]|renovate-bot|@github-actions-bot|dependabot\[bot\]|ImgBotApp)
          avatarSize: 42

      - name: Modify README.md
        run: |
          escapedHtmlList=$(echo -e '${{steps.contributors.outputs.htmlList}}' | sed ':a;N;$!ba;s/\n/\\r\\n/g;s/\\r\\n$//')
          startMarker='<!--AUTO_GENERATED_PLEASE_DONT_DELETE_IT-->'
          endMarker='<!--AUTO_GENERATED_PLEASE_DONT_DELETE_IT-END-->'
          sed -i "/$startMarker/,/$endMarker/c\\$startMarker$escapedHtmlList$endMarker" README.md
          cat README.md
          git diff --quiet --exit-code README.md || echo "CHANGES_DETECTED=true" >> $GITHUB_ENV

      - name: Commit and push README.md
        if: ${{ env.CHANGES_DETECTED == 'true' }}
        run: |
          bash script/ci_commit_with_signature.sh \
          ${{ secrets.CI_GITHUB_TOKEN }} \
          ${{ github.repository }} \
          "README.md" \
          "修改文档: 更新\`贡献者列表\`" \
          "Signed-off-by: 沙漠之子 <7850715+maboloshi@users.noreply.github.com>"
